### ISSUE TITLE
Sentry appears in the nether [1.10.2-3.2.3]

### ISSUE THREAD

**Issue by charlesbevans** [ToroCraft/ToroQuest#147] opened 2017-05-08 18:55 UTC
I went to the nether and a sentry spawned some distance from my portal. He picked a fight with some pigmen who promptly aggroed on me. My base/portal was right outside a town and I had ally status.

**Comment by frodare** [comment] 2017-05-08 20:36
This bug has been reported before but I was unable to reproduce it.  However, no I am looking back at it I think I will be able to fix the problem. I will include the a fix for this in the next release.  Thanks!

Notes: add DIMID check to: https://github.com/ToroCraft/ToroQuest/blob/master/java/net/torocraft/toroquest/civilization/CivilizationHandlers.java#L450

**Comment by frodare** [comment] 2017-05-18 03:36
I changed the code to check the dimension before spawning the sentries, which should fix this issue.  I will try to release the new version within a few days.

**Closed by frodare** 2017-05-18 03:36 UTC
Labels: bug

**Comment by frodare** [comment] 2017-05-19 11:25
ToroQuest 1.11.2-3.5 is now on curse with a fix for this issue.

**Comment by DAmnshaYmZ** [comment] 2017-07-19 03:01
Hello,

Is there any chance you could implement the Sentries in the Nether fix for the 1.10.2 version?  Thanks.
